2022-03-06 06:57:24,511 ERROR: Exception on /index [GET] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 25, in index
    return render_template('index.html',
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bbird\diary\app\templates\index.html", line 8, in template
    <meta property="og:url" content="{{url_for('main_bp.index'}}">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2022-03-06 06:58:04,212 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-03-06 07:21:58,957 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-03-12 21:51:39,581 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-03-12 21:54:13,848 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-03-12 21:54:43,436 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-03-12 21:55:05,596 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-04-04 09:28:38,259 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:85]
2022-04-04 09:30:18,915 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:85]
2022-04-04 09:49:02,327 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:85]
2022-04-04 11:11:46,246 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 13:42:27,379 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 13:45:29,970 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 13:47:26,881 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 13:51:14,621 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:08:01,475 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:09:12,948 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:12:10,554 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:13:39,917 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:14:05,124 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:22:12,109 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:24:22,448 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:31:38,606 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:33:24,548 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:37:20,415 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:49:12,842 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:49:36,856 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:50:14,804 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:50:37,177 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:53:17,812 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:54:33,905 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:54:59,860 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:55:26,685 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 14:58:57,343 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:00:12,668 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:01:47,121 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:07:01,634 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:14:03,751 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:18:05,859 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:18:08,962 ERROR: Exception on /comments/1 [GET] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 127, in comments
    return render_template("comments.html",title="My Diary",post=post)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bbird\diary\app\templates\comments.html", line 1, in top-level template code
    {% extends "layouts/base.html" %}
  File "C:\Users\bbird\diary\app\templates\layouts\base.html", line 144, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\bbird\diary\app\templates\comments.html", line 17, in block 'content'
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'csrf_token' is undefined
2022-10-07 15:18:13,376 ERROR: Exception on /comments/1 [GET] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 127, in comments
    return render_template("comments.html",title="My Diary",post=post)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bbird\diary\app\templates\comments.html", line 1, in top-level template code
    {% extends "layouts/base.html" %}
  File "C:\Users\bbird\diary\app\templates\layouts\base.html", line 144, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\bbird\diary\app\templates\comments.html", line 17, in block 'content'
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'csrf_token' is undefined
